### ISSUE TITLE
Feature request: Commit Event

### ISSUE THREAD

**Issue by kaustav202** [Readme-Workflows/recent-activity#190]
### Checks

- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing feature requests.

### Description

Is there a possibility of adding a commits event as well to the supported events?
That would allow to keep track of all the recent commits as that is the only major activity missing.

**Comment by Andre601** [comment]
What do you mean with "secret commits"? If you mean commits towards a private repository, then you have to use a Personal Access Token with the `repo` scope, as events related to private repositories are not something accessible in GitHub's Public Events API using the default GitHub Token (It may not even work at all. Depends on how the Events API behaves with what token).

**Comment by kaustav202** [comment]
No I meant public commits only!!

**Comment by abhijoshi2k** [comment]
It is possible to add. However, since commits are quite frequent events. It would displace more significant events immediately.
So the commit event has not been added.

What are your views @Andre601 @PuneetGopinath ?

**Comment by Andre601** [comment]
If it was added, then it should be disabled by default similar to the comments activity.

**Comment by abhijoshi2k** [comment]
As of current version, we cannot disable events by default. User will have to do it manually.
This was done in one of the previous releases to fix an issue.
