### ISSUE TITLE
Feature request: support for multiple readme files

### ISSUE THREAD

**Issue by fbuireu** [Readme-Workflows/recent-activity#211]
### Checks

- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing feature requests.

### Description

Hi guys!

I'm planning to migrate to your GH action, but before that I'd like to know if you support multiple `readme_file`. My use-case is that I have a 4 language profile (one `README.md` per language) and I'm using a matrix to loop through. 

Since your `v2` configuration, I've noticed that you use a configuration file where all the details (`readme_file`, etc) are stored. As is, this will force me to use 4 separates configuration files (one per language) unless it supports an array-like structure:

```js
readme_file: ["README_1.md", "README_2.md",]
```

Is this actually a feature? I really would like to have it. 

Thanks for your effort

### Alternatives considered

I've tried to use the deprecated `v.1.3.0` to use a `README_FILE` `with` option, but it doesn't work.

**Comment by abhijoshi2k** [comment]
Hello @fbuireu Thanks for the request.
However, currently I'm the only one who maintains the core coding part and I cannot dedicate the amount of time required for this feature implementation.
Also, having different configuration files is the easiest way to achieve your goal. I would recommend that.

**Comment by Andre601** [comment]
I agree on the fact that a Matrix is (for now) the best solution here, especially in your use-case where you probably also want to change the messages used for the activity displayed. Doesn't make much sense to have english text on something like an Italian readme file.
