### ISSUE TITLE
Feature request: Option for toggling numbers

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [Readme-Workflows/recent-activity#220]
### Checks

- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing feature requests.

### Description

I think a toggle option should be added to Recent Activity, which allows us to toggle the numbers next to each event. So we can turn them on (default) or turn them off if we don't want the numbers list.

**Comment by abhijoshi2k** [comment]
It's a good idea.
I shall try to implement it when I get time (probably by end of month)

**Comment by WilliamDavidHarrison** [comment]
Thanks!

**Comment by WilliamDavidHarrison** [comment]
@abhijoshi2k Any updates?

**Comment by abhijoshi2k** [comment]
Hi @WilliamDavidHarrison so sorry for delayed response. However, I'm unable to find bandwidth for implementing this. I'll mark this as `help-wanted`. Let's see if someone can create a PR.
At the same time, I'll implement it if I find some time.

**Comment by abhijoshi2k** [comment]
Created a draft PR for this. Will add the feature soon.

**Comment by WilliamDavidHarrison** [comment]
Ok
