### ISSUE TITLE
Feature request: Ignoring repos

### ISSUE THREAD

**Issue by SrIzan10** [Readme-Workflows/recent-activity#223]
### Checks

- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing feature requests.

### Description

I have some upptime instances on some Github repos and on the readme it keeps popping up the commits made by the bot. Is there any way to ignore those repos and show only the "real" commits?

**Comment by abhijoshi2k** [comment]
I currently don't have the bandwidth to work on this. I've added `help wanted` label as of now.

**Comment by adityajoshi12** [comment]
Please assign to me, I will take this.
