### ISSUE TITLE
Bug report: Unable to resolve action `Readme-Workflows/recent-activity@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by PuneetGopinath** [Readme-Workflows/recent-activity#23]
Please check these things before submitting your issue:

- [x] I am using the latest version
- [x] I searched for duplicate or closed bug report [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Describe the bug**
GitHub actions doesn't find version v1

**To Reproduce**
1. Go to 'Any of your GitHub repo'
2. Click on 'Actions tab'
3. Run the 'recent-activity workflow with v1'

**Expected behavior**
Expected to work Normally

**Screenshots**
N/A

**Additional context**
See https://github.com/PuneetGopinath/PuneetGopinath/runs/2565219045?check_suite_focus=true

**Comment by Andre601** [comment]
Is that a test for issue templates and/or the welcome bot or something?

**Comment by abhijoshi2k** [comment]
@PuneetGopinath But latest version is working fine.
Can you explain more about this?

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath But latest version is working fine.
> Can you explain more about this?

Nop, in your workflow you are using branch main, anyway now we released v1.2.1 but still it doesn't work

Or could be a bug with github actions itself?

**Comment by PuneetGopinath** [comment]
> Is that a test for issue templates and/or the welcome bot or something?

Not any test

**Comment by PuneetGopinath** [comment]
Wait a se, line 26 shows `Failed to resolve action download info.`

**Comment by abhijoshi2k** [comment]
> Wait a sec, line 26 shows `Failed to resolve action download info.`

Which file are you talking about?

**Comment by PuneetGopinath** [comment]
> Which file are you talking about?

No any file, line 26 in [workflow run](https://github.com/PuneetGopinath/PuneetGopinath/runs/2565219045?check_suite_focus=true)

**Comment by Andre601** [comment]
> > Which file are you talking about?
> 
> Not any file, line 26 in [workflow run](https://github.com/PuneetGopinath/PuneetGopinath/runs/2565219045?check_suite_focus=true)

You are aware that v1 is NOT an actual release hee right?

**Comment by abhijoshi2k** [comment]
Just make changes in your `.yml` file accordingly. Update it to point to recent version `v1.2.1` / `main` branch.

**Comment by PuneetGopinath** [comment]
> > > Which file are you talking about?
> > 
> > 
> > Not any file, line 26 in [workflow run](https://github.com/PuneetGopinath/PuneetGopinath/runs/2565219045?check_suite_focus=true)
> 
> You are aware that v1 is NOT an actual release hee right?

Yes, I just forgot it
I got confused
Sorry guys
