### ISSUE TITLE
Feature request: {version} placeholder should be more explained

### ISSUE THREAD

**Issue by gab-villa** [Readme-Workflows/recent-activity#267]
### Checks

- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing feature requests.

### Description

i don't know why the workflow action simply doesn't accept any version (i tested with v2.4.1, 2.4.1, v2.x, v2, etc). i had to test with "main" and it works perfectly. i'm not sure if i did terribly bad, but i'd be thankful if someone could explain me what happened that

**Comment by abhijoshi2k** [comment]
You do not have to use curly braces (as I observed in one of your failed workflows).
There is a general syntax of GitHub workflows to address as `{org_name}/{repo_name}@{version}`
For example, you can use: `Readme-Workflows/recent-activity@v2.4.1`
We do not feel that this general syntax (which is followed all over GitHub) needs a specialized documentation from our end.
However, if this does not work, please put a link of the failed workflow here and we will check.

**Comment by abhijoshi2k** [comment]
Closing this issue as of now. Can be reopened if you still face issues.
