### ISSUE TITLE
Bug report: Error: Invalid status code: 1

### ISSUE THREAD

**Issue by PuneetGopinath** [Readme-Workflows/recent-activity#27]
Please check these things before submitting your issue:

- [x] I am using the latest version
- [x] I searched for duplicate or closed bug report [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Describe the bug**
The same `Invalid status code: 1`, see [my workflow run](https://github.com/PuneetGopinath/PuneetGopinath/runs/2581258476?check_suite_focus=true)

**To Reproduce**
1. Go to 'Your profile readme'
2. Click on 'Actions'
3. Scroll down to 'A workflow run'

**Expected behavior**
Expected to work well.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by abhijoshi2k** [comment]
It's working on `main` branch. Maybe we should release again?

**Comment by PuneetGopinath** [comment]
> It's working on `main` branch. Maybe we should release again?

I think no use of releasing again, we didn't change anything to build/index.js after releasing

**Comment by abhijoshi2k** [comment]
The build changed after the last release. Even just now when I run build, it changed.

**Comment by PuneetGopinath** [comment]
Ohh, maybe before releasing last time we didn't run build

**Comment by PuneetGopinath** [comment]
I think we are wasting time running build, should setup a GitHub action for that

**Comment by abhijoshi2k** [comment]
I'll do it

**Comment by PuneetGopinath** [comment]
Ok, release v1.2.2

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PuneetGopinath** [comment]
Ok, release v1.2.2

**Comment by Andre601** [comment]
The action works perfectly fine for me tho. I use v1.2.1
