### ISSUE TITLE
Bug report: Timezone offset potential issue

### ISSUE THREAD

**Issue by StevenJDH** [Readme-Workflows/recent-activity#49]
Please check these things before submitting your issue:

- [x] I am using the latest version
- [x] I searched for duplicate or closed bug report [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Describe the bug**
I love the new changes with last update and timezone details, but I believe there will be an issue here related to this. For example, there are countries, or maybe just Spain, who's timezone changes during daylight savings time. During DST, the majority of Spain uses +2 for the offset, but outside of DST, it's +1 as the offset. I have the same issue with my DSLR camera where I have to change this twice a year because it uses offsets rather than just selecting a region/capital. I am not sure if this is something that can be fixed or if it is considered a bug, but I thought it is worth mentioning. Perhaps the best solution is just to keep it neutral at GTM 0.

**To Reproduce**
It's time based so maybe make a run during DST and outside of DST changing the local date as per references below.

**Expected behavior**
It would be nice to be able to set by region|capital and have the library workout the correct offset.

**Screenshots**
N/A

**Additional context**
You can see references for both of these shifting timezones here:
https://www.timeanddate.com/time/zone/spain/madrid
https://en.wikipedia.org/wiki/Time_in_Spain#IANA_time_zone_database

**Comment by Andre601** [comment]
Hey there. We will look into this and there are possible ways to change the timezone within JavaScript, so expect a PR for this in the future (no ETA tho)

Also, you're not the only one suffering from Daylight saving. In Switzerland, where I live, is this also the case, changing from +1 to +2 hours or vice-versa, so you're not alone 😉

**Comment by StevenJDH** [comment]
Sounds good, and no rush.

Interesting, I did not know that about Switzerland. I wonder how common it is now. Anyways, thanks for taking over this project 🙂

**Comment by PuneetGopinath** [comment]
@Andre601 Node.js is not the same JavaScript, we can't change any timezone in Node.js, maybe @abhijoshi2k Can do it using the `dateformat` package we have as dependency. I will too check out how to do it.

**Comment by PuneetGopinath** [comment]
@StevenJDH  I added the `Priority: medium` label as I consider medium priority for this, even I think it can be set to low also because we are not going to daily open the recent activity of ours. I think for now you can use GMT timezone itself 👍

**Comment by abhijoshi2k** [comment]
> @Andre601 Node.js is not the same JavaScript, we can't change any timezone in Node.js, maybe @abhijoshi2k Can do it using the `dateformat` package we have as dependency. I will too check out how to do it.

There is a way to do it in node.js
Although I'll need to check if it supports DST. We can temporarily change the timezone of system.
