### ISSUE TITLE
Bug report: disabled_events setting not working as expected

### ISSUE THREAD

**Issue by StevenJDH** [Readme-Workflows/recent-activity#58]
Please check these things before submitting your issue:

- [x] I am using the latest version
- [x] I searched for duplicate or closed bug report [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Describe the bug**
This might be user error, but with regards to the `disabled_events` setting, there isn't a reference in the documentation or an indication for what event names are available. In my case, instead of using `comments` as in the example, I used `new_star`, but it didn't work assuming it's the same as the messages section which also has `comments`. I also couldn't find any clear documentation from GitHub. I haven't tried `starred` yet.

This is more of a question, not a bug, but it could be useful to add some kind of reference in the documentation for this setting just to dummy proof it.

**To Reproduce**
1. Use `new_star` in `disabled_events`.
2. Star a repo.
3. Run the workflow, and review the result.

**Expected behavior**
A clear understanding on what event names to use, and when used, they work. A GitHub doc reference in the documentation would be best since based on the output of the action there are 100s.

**Screenshots**
N/A

**Comment by Andre601** [comment]
Could you try `star`?
That's what I can find within the code.

**Comment by Andre601** [comment]
I went ahead and updated the wiki with the missing options for the [`disabled_events`](https://github.com/Readme-Workflows/recent-activity/wiki/Configuration#disabled_events)

**Comment by StevenJDH** [comment]
Adding `star` works, thanks. The table with events was a nice add, it's very clear now because I was even looking at `curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/users/{username}/events/public`, which shows star events as `WatchEvent`, but even this wasn't correct, so this table is needed. 

Issue is solved with that documentation update.

**Comment by PuneetGopinath** [comment]
> I went ahead and updated the wiki with the missing options for the [`disabled_events`](https://github.com/Readme-Workflows/recent-activity/wiki/Configuration#disabled_events)

Hey Andre, by default comments are not disabled
