### ISSUE TITLE
Setup Airbrake for your Node application

### ISSUE THREAD

**Issue by PuneetGopinath** [Readme-Workflows/recent-activity#60]
### **Installation**

Add the <a href="https://www.npmjs.com/package/@airbrake/node" class="external-link">library</a>

```sh
npm install @airbrake/node
```

### **Configuration**

This is a simple Node app `app.js` file that throws an error and sends it to Airbrake. To configure Airbrake in your project, `require` our library and instantiate it with your project credentials:

<small>(You can find your project ID and API key in your [project's settings](https://airbrake.io/projects/336130/edit))</small>

```js
const http = require('http');
const Airbrake = require('@airbrake/node');

new Airbrake.Notifier({
  projectId: <Your project ID>,
  projectKey: '<Your project API key>',
  environment: 'production'
});

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((_req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
  throw new Error('I am an uncaught exception');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

### **Full documentation**

Visit our <a href="https://github.com/airbrake/airbrake-js/tree/master/packages/node" class="external-link">official GitHub repo</a> for more examples and info on advanced options.

**Comment by PuneetGopinath** [comment]
@abhijoshi2k I didn't open this issue, I think airbrake did it

**Comment by abhijoshi2k** [comment]
> @abhijoshi2k I didn't open this issue, I think airbrake did it

Same thing happened when I logged in from my account
