### ISSUE TITLE
Feature request: Add support for turning PRs into draft or ready to review

### ISSUE THREAD

**Issue by Andre601** [Readme-Workflows/recent-activity#72]
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
According to a response on github.community is a PullRequestEvent fired whenever a user turns a draft-PR into an actual PR or vice-versa.
The `action` key in those cases seems to be either `converted_to_draft` when turning it into a draft or `ready_for_review` for when it becomes an actual PR.

I now suggest to implement support for this to allow the following cases to be displayed in the action's list:

- Creating normal PR
- Creating Draft PR
- Turning normal PR into Draft PR
- Turning Draft PR into normal PR

**Describe alternatives you've considered**

**Additional context**
See [this response](https://github.community/t/what-event-is-triggered-for-turning-a-draft-pr-into-a-pr/180088/2?u=andre601) for context.

**Comment by Andre601** [comment]
Looking at the public event list, it seems like that this event type isn't a thing, or at least not accessible without extra authentication...
So this may not work actually.

**Comment by PuneetGopinath** [comment]
Andre, this thing is already tested by me.
I opened a pr for a small change and it was a draft at first, after that I converted it into a normal pr. I got no new PullRequestEvent event fired.
